name: Extension Method
description: Have an idea to simplify a very repetative process for a specific type? While extension methods have a bad reputation, when implemented properly, they can be very powerful.
labels: [feature request,framework,under review]
body:
  - type: textarea
    attributes:
      label: 😭 What problem does your proposition aim to solve?
      description: If your feature request is related to a problem, describe it clearly.