name: Feature Request (Fancy)
description: Request a cool new feature for the project.
labels: [feature request]
body:
  - type: textarea
    attributes:
      label: 😭 What problem does your proposition aim to solve?
      description: If your feature request is related to a problem, describe it clearly.
      placeholder: When I'm using a `foreach` loop, I can't get the next or previous element in my collection without having a separate variable or overly verbose code.
  - type: markdown
    attributes:
      value: |
        "📝 How would you like it to work?"
        Please give a brief explanation and a sample implementation. For example:
        > I would like to be able to use a `LINQ` style method to get the next element, for example:
        >
        > ```csharp
        > foreach (var item in collection) {
        >     var nextItem = collection.NextOrDefault(item);
        >     var previousItem = collection.PreviousOrDefault(item);
        > }
        > ```
  - type: textarea
    attributes:
      label: 🎲 What have you already tried?
      description: Describe alternatives you've considered
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ---

        Test of markdown area.
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: 🔢 Which version of Mauve are you currently using?
      options:
        - Pre-Release
    validations:
      required: true
  - type: textarea
    attributes:
      label: Comments
      description: Additional information, comments or screenshots about the feature request.