name: Build
 
on: [push]
 
jobs:
  build:
 
    runs-on: windows-latest
 
    steps:
    - uses: actions/checkout@v2
     
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
 
    - name: Build Solution
      run: |
        msbuild.exe Mauve.sln /nologo /nr:false /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release"
